### ISSUE TITLE
As a user, I would like to view the peoples covid information so that I can make the correct decision for that person 

### ISSUE THREAD

**Issue by BunnyPrince** [AC159/SOEN_390#13]
### **Description:**

The users are the health officer and the immigration officer. The health officer will be able to see all peoples covid info page. The immigration officer will be able to see the travelers covid info page.

### **Steps:**

- [x] Create a page with the list of patient/ travelers 
- [x] Create a covid info page for a person that will  display all information of that person like their symptoms 

### **Acceptance Test Steps:**
- Log in using health officer/ immigration officer credentials and land on the health officer/ immigration officer home page
- Click on the patient/traveler tap to see the list 
- Click on a person to be redirected to their covid info page

**Comment by DrakeHunterK7** [comment]
Great job, it is done
