### ISSUE TITLE
As an administrator, I would like to assign a user to a specific role so that they have access to their respective user features

### ISSUE THREAD

**Issue by ani-6292** [AC159/SOEN_390#17]
### **Description:**

Users will be assigned to a default role. The administrator will be notified when a user wants to change their role. The administrator will then assign the user to their new role. 

### **Steps:**

- [ ] Send a notification to the admin when a user wants to change roles
- [ ] Create a page with a list of users with a button to change their role
- [ ] Implement a display with the list of roles to show up when the button is clicked
- [ ] Save the newly assigned role and update the database

### **Acceptance Test Steps:**
- Log in using administrator credentials and land on the administrator home page.
- Click on the notification page to get the request of the user
- Go to user list page
- Click on the “role” button next to the specific user
- Click on the role requested by the user
- Click save to assign the new role to the user
- The user should have access to the features of to their newly assigned role

**Comment by BunnyPrince** [comment]
Completed for sprint 1
