### ISSUE TITLE
As a doctor, I would like to see the data of the covid cases in a visual format so that I can have an overall view of the situation

### ISSUE THREAD

**Issue by BunnyPrince** [AC159/SOEN_390#21]
### **Description:**

The page will display a list of patients with their covid status next to their name.

### **Steps:**

- [ ] Create a visual format to be shown at the top of the page to display the covid cases

### **Acceptance Test Steps:**
- Log in using doctor credentials and land on the doctor home page.
- A visual display should be seen of the patient data at the top and a list of patient with their covid status at the bottom

**Comment by DrakeHunterK7** [comment]
- graphs and statistics to visualize trends/distribution of key symptom parameters
- Potentially aggregated display for Health Official of all patients
