### ISSUE TITLE
Bug - Lack of Feedback on doctor appointment form

### ISSUE THREAD

**Issue by p-carrier** [AC159/SOEN_390#77]
# General info
The form is lacking feedback so it's hard to know if we are doing something in it. For example the date element is missing a concrete visual representation of date selection. 
Also, when submitting the form, the button doesn't provide adequate feedback to know that we have submit the form.

**Task description**: 

 - Add visual effect to show that a date is selected. 
 - Add a visual effect to the submit button for hover and active
 
 
<img width="515" alt="Screen Shot 2022-03-16 at 11 31 17 PM" src="https://user-images.githubusercontent.com/29782830/158731323-04220ae8-2923-4a87-994b-c157c03083a3.png">

**Comment by mth-1012** [comment]
Done. After clicking "Book Appointment", an alert is shown and the appointment form is cleared.
